<a href="https://colab.research.google.com/github/SODAx12/bank-customer-prediction/blob/main/bank_customer_pred_(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [ ]:
tf.__version__

'2.8.2'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset=pd.read_csv('/content/drive/MyDrive/ML/Customer_data.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [ ]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [ ]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)
print(xtrain)

## Part 2 - Building the ANN

In [ ]:
ann=tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=8,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(xtrain,ytrain,batch_size=30,epochs=150)

Epoch 1/150
267/267 [==============================] - 1s 2ms/step - loss: 0.6233 - accuracy: 0.8476
Epoch 2/150
267/267 [==============================] - 0s 2ms/step - loss: 0.4957 - accuracy: 0.8654
Epoch 3/150
267/267 [==============================] - 0s 2ms/step - loss: 0.4101 - accuracy: 0.8673
Epoch 4/150
267/267 [==============================] - 0s 2ms/step - loss: 0.3693 - accuracy: 0.8660
Epoch 5/150
267/267 [==============================] - 0s 2ms/step - loss: 0.3523 - accuracy: 0.8677
Epoch 6/150
267/267 [==============================] - 0s 2ms/step - loss: 0.3430 - accuracy: 0.8685
Epoch 7/150
267/267 [==============================] - 0s 2ms/step - loss: 0.3392 - accuracy: 0.8675
Epoch 8/150
267/267 [==============================] - 0s 2ms/step - loss: 0.3352 - accuracy: 0.8656
Epoch 9/150
267/267 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8692
Epoch 10/150
267/267 [==============================] - 0s 2ms/step - loss: 0.3313 - accura

**Solution**

## Part 4 Evaluating the model

### Predicting the Test set results

In [ ]:
ypred=ann.predict(xtest)
ypred = (ypred > 0.5)
print(np.concatenate((ypred.reshape(len(ypred),1),ytest.reshape(len(ytest),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 191  214]]


0.8605

### Predicting the result of a single observation

In [ ]:
cs,age,tn,bal,p,s=input("ENTER CREDIT SCORE, AGE, TENURE, BALANCE, number of PRODUCTS, SALARY(in $): (IN SAME ORDER)  ").split()
s1,s2,s3=input("ENTER 1 0 0 if COUNTRY is FRANCE  0 1 0 if COUNTRY is GERMANY  0 0 1 if COUNTRY is SPAIN  ").split()
g=input("ENTER 0 if You Are Female  or 1 if You Are Male  ")
card=input("ENTER 1 if You Have Credit Card  or 0 Otherwise  ")
act=input("ENTER 1 if Active Account  or 0 Otherwise  ")
print(ann.predict(sc.transform([[float(s1),float(s2),float(s3),float(cs),float(g),float(age),float(tn),float(bal),float(p),float(card),float(act),float(s)]]))>0.5)

ENTER CREDIT SCORE, AGE, TENURE, BALANCE, number of PRODUCTS, SALARY(in $): (IN SAME ORDER)  550 25 1 20000 2 40000
ENTER 1 0 0 if COUNTRY is FRANCE  0 1 0 if COUNTRY is GERMANY  0 0 1 if COUNTRY is SPAIN  0 1 0
ENTER 0 if You Are Female  or 1 if You Are Male  1
